-- NusaHarvest V2 -- Postgres schema (docs/02-FLOW-DAN-SKEMA-FINAL.md section 4.1).
--
-- This file is the current shape of the database. It is generated by applying every
-- file in db/migrations in order; do not apply it on top of a migrated database.
-- To create a database: node db/migrate.mjs
--
-- Personal data rules (UU PDP 27/2022):
--   * every *_enc column is AES-256-GCM ciphertext produced by web/lib/crypto.ts
--     (0x01 || iv12 || tag16 || ciphertext). Plaintext phone numbers, names,
--     account numbers and coordinates never touch a column, an index or a log.
--   * every *_lookup_hmac column is HMAC-SHA256 under PII_HMAC_KEY, domain separated.
--     Duplicate checks and lookups run against these, never against plaintext.
--   * only salted hashes (phone_hash, leaf) are ever published or sent on-chain.
--   * retention: *_enc columns are erased PII_RETENTION_MONTHS (default 12) after the
--     campaign reaches RECEIPTED or REFUNDED; see pii_erasures and
--     db/migrations/0002_retention.sql for the erasure routine.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Sponsors and campaigns
-- ---------------------------------------------------------------------------

create table if not exists sponsors (
  id                 uuid primary key default gen_random_uuid(),
  legal_name         text not null,
  kind               text not null check (kind in ('csr','laz','ngo','pemda','offtaker','team')),
  wallet             text,
  contact_email_enc  bytea,
  created_at         timestamptz not null default now()
);

create table if not exists campaigns (
  id             uuid primary key default gen_random_uuid(),
  sponsor_id     uuid not null references sponsors(id),
  code           text unique not null,                       -- NH-KLT26
  pubkey         text unique,
  campaign_id    bigint not null,
  mode           text not null check (mode in ('escrow','pledge')),
  grid_cells     int[] not null,
  regency        text not null,
  province       text not null,
  historical_replay boolean not null default false,   -- spec rule 3: only on a separate cluster, always labelled
  commodity      text not null,
  freeze_ts      timestamptz not null,
  window_start   date not null,
  window_end     date not null,
  thr_full_mm10  int not null,
  thr_half_mm10  int not null,
  amount_full_idr int not null,
  amount_half_idr int not null,
  units_max      int not null check (units_max > 0),
  terms_doc_url  text,
  terms_hash     text,
  terms_doc      text,                        -- canonical JSON whose sha256 is terms_hash
  amount_full_base bigint,                    -- token base units written on chain
  amount_half_base bigint,
  rule_version   smallint not null default 1,
  status         text not null default 'draft'
                 check (status in ('draft','open','settled','disputed','settled_final','released','receipted','refunded')),
  created_tx     text,
  closed_at      timestamptz,                 -- set when status becomes receipted/refunded (retention clock)
  created_at     timestamptz not null default now(),
  check (array_length(grid_cells, 1) >= 1),
  check (thr_full_mm10 <= thr_half_mm10),
  check (amount_half_idr <= amount_full_idr),
  check (window_start <= window_end)
);
create index if not exists campaigns_status_freeze_idx on campaigns (status, freeze_ts);
create index if not exists campaigns_grid_cells_idx on campaigns using gin (grid_cells);

-- Regencies offered in the sponsor console and the 0.1 degree cells that cover them
-- (spec 2.2 E1: "pilih kabupaten, sistem memetakan sel grid"). Loaded from the BPS/BIG
-- administrative boundary layer by an operator script; never seeded with sample rows.
create table if not exists regions (
  regency     text not null,
  province    text not null,
  grid_cells  int[] not null check (array_length(grid_cells, 1) >= 1),
  source      text not null,
  loaded_at   timestamptz not null default now(),
  primary key (province, regency)
);

-- Status transitions observed on chain (timeline on the proof page).
create table if not exists campaign_events (
  id          bigserial primary key,
  campaign_id uuid not null references campaigns(id),
  status      text not null,
  tx_sig      text,
  note        text,
  at          timestamptz not null default now()
);
create index if not exists campaign_events_campaign_idx on campaign_events (campaign_id, at);

-- PostReceipts anchors.
create table if not exists receipt_posts (
  campaign_id  uuid primary key references campaigns(id),
  root         text not null,
  tx_sig       text,
  paid_count   int not null,
  failed_count int not null,
  total_paid_idr bigint not null,
  manual_disbursement boolean not null default false,
  posted_at    timestamptz not null default now()
);

-- Grid cells excluded from enrolment (technically irrigated paddy, spec 2.3).
-- Loaded from the published irrigation layer; an empty table means no exclusions.
create table if not exists excluded_cells (
  grid_cell int primary key,
  reason    text not null,
  source    text not null,
  loaded_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Enrolments
-- ---------------------------------------------------------------------------

create table if not exists enrollments (
  id                          uuid primary key default gen_random_uuid(),
  campaign_id                 uuid not null references campaigns(id),
  phone_enc                   bytea not null,
  phone_lookup_hmac           text not null,
  payout_channel              text check (payout_channel in ('dana','gopay','ovo','shopeepay','bank')),
  payout_account_enc          bytea,
  payout_account_lookup_hmac  text,
  payout_name_masked          text,
  payout_name_verified        boolean not null default false,
  lat_enc                     bytea,
  lon_enc                     bytea,
  plot_lookup_hmac            text,                 -- HMAC of the ~22 m coordinate cell, for the <20 m duplicate rule
  grid_cell                   int,
  salt                        bytea not null,
  proof_code                  text not null,
  leaf                        text not null,
  status                      text not null check (status in ('valid','waitlist','rejected','withdrawn')),
  reject_reason               text,
  assisted_by                 text,
  locked_at                   timestamptz,          -- set when the leaf entered a LockRoster tx
  pii_erased_at               timestamptz,
  created_at                  timestamptz not null default now(),
  unique (campaign_id, phone_lookup_hmac)
);
create unique index if not exists enrollments_campaign_account_idx
  on enrollments (campaign_id, payout_account_lookup_hmac)
  where payout_account_lookup_hmac is not null and status in ('valid','waitlist');
create index if not exists enrollments_campaign_plot_idx on enrollments (campaign_id, plot_lookup_hmac);
create index if not exists enrollments_campaign_status_idx on enrollments (campaign_id, status);
create unique index if not exists enrollments_campaign_leaf_idx on enrollments (campaign_id, leaf);
create index if not exists enrollments_proof_code_idx on enrollments (proof_code);

-- ---------------------------------------------------------------------------
-- Merkle trees and on-chain anchors
-- ---------------------------------------------------------------------------

create table if not exists roster_locks (
  id          bigserial primary key,
  campaign_id uuid not null references campaigns(id),
  units       int not null,
  root        text not null,
  tx_sig      text,
  created_at  timestamptz not null default now()
);
create index if not exists roster_locks_campaign_idx on roster_locks (campaign_id, created_at desc);

create table if not exists merkle_nodes (
  campaign_id uuid not null references campaigns(id),
  tree        text not null check (tree in ('roster','receipts')),
  level       smallint not null,
  idx         int not null,
  hash        text not null,
  primary key (campaign_id, tree, level, idx)
);
create index if not exists merkle_nodes_leaf_idx on merkle_nodes (campaign_id, tree, hash) where level = 0;

-- ---------------------------------------------------------------------------
-- Climate and settlement
-- ---------------------------------------------------------------------------

create table if not exists climate_snapshots (
  grid_cell  int not null,
  source     text not null,
  day        date not null,
  rain_mm    numeric,
  rain_mm100 int,
  raw_sha256 text not null,
  fetched_at timestamptz not null default now(),
  primary key (grid_cell, source, day)
);

create table if not exists settlements (
  campaign_id    uuid primary key references campaigns(id),
  observed_mm10  int,
  secondary_mm10 int,
  divergence_bp  int,
  outcome        text check (outcome in ('FULL','HALF','NONE')),
  data_json      text,
  data_json_url  text,
  data_hash      text,
  script_commit  text,
  tx_sig         text,
  settled_ts     timestamptz,
  review         boolean not null default false,
  review_note    text,
  review_cleared_by text,
  review_cleared_at timestamptz,
  created_at     timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Payouts and messaging
-- ---------------------------------------------------------------------------

create table if not exists payouts (
  enrollment_id    uuid primary key references enrollments(id),
  campaign_id      uuid not null references campaigns(id),
  amount_idr       int not null,
  gateway          text,
  gateway_ref_hash text,
  status           text not null default 'pending'
                   check (status in ('pending','sent','paid','failed','abandoned')),
  attempts         int not null default 0,
  last_error       text,
  paid_at          timestamptz,
  receipt_leaf     text,
  updated_at       timestamptz not null default now()
);
create index if not exists payouts_campaign_status_idx on payouts (campaign_id, status);

create table if not exists message_log (
  id            bigserial primary key,
  enrollment_id uuid references enrollments(id),
  campaign_id   uuid references campaigns(id),
  phone_lookup_hmac text,                       -- never the number itself
  direction     text not null check (direction in ('in','out')),
  template      text not null,
  wa_message_id text,
  transport     text not null default 'meta',
  error         text,
  created_at    timestamptz not null default now()
);
create index if not exists message_log_phone_idx on message_log (phone_lookup_hmac, created_at desc);

-- Inbound WhatsApp message ids already processed. Meta retries on any non-200,
-- so every handler is idempotent on this table.
create table if not exists wa_inbound (
  wa_message_id text primary key,
  received_at   timestamptz not null default now()
);

-- Conversation state for the registration bot (spec 2.3). Keyed by HMAC, never by number.
create table if not exists wa_sessions (
  phone_lookup_hmac text primary key,
  campaign_id       uuid references campaigns(id),
  state             text not null check (state in
                      ('idle','awaiting_consent','awaiting_location','awaiting_channel',
                       'awaiting_account','awaiting_name_confirm','done')),
  draft             jsonb not null default '{}'::jsonb,   -- ciphertext + non-PII scratch only
  lang              text not null default 'id' check (lang in ('id','en')),
  opted_out         boolean not null default false,
  updated_at        timestamptz not null default now(),
  expires_at        timestamptz not null
);
create index if not exists wa_sessions_expiry_idx on wa_sessions (expires_at);

-- ---------------------------------------------------------------------------
-- Rate limiting (public proof/lookup endpoints) and PII erasure ledger
-- ---------------------------------------------------------------------------

create table if not exists rate_limits (
  bucket       text not null,
  window_start timestamptz not null,
  count        int not null default 0,
  primary key (bucket, window_start)
);
create index if not exists rate_limits_window_idx on rate_limits (window_start);

-- Append-only record of every erasure: scheduled retention runs and data-subject
-- requests under UU PDP 27/2022 art. 8 (right to erasure). Holds no personal data.
create table if not exists pii_erasures (
  id           bigserial primary key,
  scope        text not null check (scope in ('retention','subject_request','campaign')),
  campaign_id  uuid references campaigns(id),
  subject_hmac text,
  rows_erased  int not null default 0,
  reason       text not null,
  requested_at timestamptz not null default now(),
  erased_at    timestamptz
);
